### ISSUE TITLE
phplint renamed to phpl 

### ISSUE THREAD

**Issue by SachaMPS** [SublimeLinter/SublimeLinter-phplint#14]
I just tried to install the linter and got an error: phplint not found. As it seems the latest version installed via homebrew populated "phpl" and not "phplint" as the executable.

**Comment by lucidlips** [comment]
I am having this exact issue sacha, do you know if this is reason why sublimelinter cant find phplint? 

I have just switched from ST2 to ST3 and this phplint installation has me completely stuck. I have spent hours going over the setup process as I was sure I was doing something wrong. I noticed the brew installation name didn't match the sublime linter name but assumed that wasnt the source of my problem.

Hopefully someone can help with this.

**Comment by grotewold** [comment]
merged in with #13
