### ISSUE TITLE
Windows phplint 1.x incompatibility causes hang, etc

### ISSUE THREAD

**Issue by FireSBurnsmuP** [SublimeLinter/SublimeLinter-phplint#16]
As said: the recent compatibility drop of phplint < 2.0 was causing a weird error on my windows machine that I managed to get around, finding the new version requirement after digging and messing around with my phplint install.
Turns out this is related to #13, but I will get to that.

I came in this morning, and Sublime (3) froze while loading as it opened up notepad to an empty file titled "phpl-report.txt".
After closing it (and consequently un-freezing sublime) and opening the sublime console, I find this error:
```
SublimeLinter: WARNING: no phplint version could be extracted from: 
The system cannot find the path specified.(CR)
```
I couldn't figure it out, so I came here. The first thing I noticed was the [commit note](https://github.com/SublimeLinter/SublimeLinter-phplint/commit/ea725b07d0de57e1cf6e33922e22603e8eca2dae) on linter.py stating that the command had been switched from 'phplint' to 'phpl'. Well there we go: `phpl.bat` is a batch script wrapper for `phplint.exe` on windows in v1.1, at least in my installation (which I honestly don't remember where I got it from. Probably as official as I could, since this is my work pc and I don't take chances).
phpl.bat:
```
@echo off
rem PHPL.BAT - Invokes PHPLint with common options
rem Syntax:
rem
rem     phpl OPTIONS source.php
rem
rem Options:
rem
rem     See `phpl --help' for a complete list of the available options.

rem Preferred text editor:
set editor=notepad
rem set editor="C:\Program Files\Notepad++\notepad++"

rem Base directory of the PHPLint program:
set base=%~dp0

"%base%src\phplint.exe" ^
	--version ^
	--tab-size 8 ^
	--print-source ^
	--print-path shortest ^
	--modules-path "%base%modules" ^
	--print-context ^
	%* > "%TMP%/phpl-report.txt"

%editor% "%TMP%/phpl-report.txt"

```
You'll notice that this was why notepad was getting opened and freezing sublime: SublimeLinter was trying to get `phpl --version`, which was actually opening notepad, waiting then for notepad to return the output it was expecting (which it obviously did not). Even after fixing phpl.bat to have the right directory structure assumptions, it would still just put the version information in the text file and open it, which SublimeLinter then never received.

After all this, I just copied phplint.exe to phpl.exe and finally got the console error:
```
SublimeLinter: WARNING: phplint deactivated, version requirement (>= 2.0) not fulfilled by 1.1 
```

So now I know that an upgrade is in order. My phplint install isn't new enough.

It should also be noted that the phplint linter is disabled (through the SublimeLinter menu, `"@disable": true` in preferences) on my install right now, and this was still happening.

I now see that there are upgrade notes stating this requirement from your merge 5 days ago, but I must have missed them; I had issues with an upgrade to my theme this morning, too, so they probably got lost in all the graphical corruption while I was busy fixing that. It's good to see that the version requirement is in the README, although I didn't notice that until I had already found out the hard way.

Anyway, I don't know if there is really anything you can do about this, but it would be nice for other windows phplint 1.x users to not have to go through all that just to learn they need to upgrade phplint, in case they missed the upgrade notes from Package Control.

If nothing else, this will serve as a record of what to do about "WARNING: no phplint version could be extracted from:" error, for which there were previously no Google search results.
What to do? upgrade phplint.

**Comment by grotewold** [comment]
Sorry for the inconvenience! Trust me, I understand the pains of debug something like this, where it's not documented well enough yet to know how to fix it. I'll leave this open for a couple weeks to hopefully catch the eyes of the confused and wandering. 

Thanks for your help in getting the word out!

**Comment by FireSBurnsmuP** [comment]
Thanks! That's all I hope for.
After opening it up on another windows computer, I can also confirm that the upgrade notes aren't shown by Package Control. Package Control did just update to 3.1 in both cases, though, so perhaps that causes the miss of your upgrade release notes. However, the reloaded SublimeLinter-phplint package does pop up notepad again (Although on this computer it actually displayed the version information the first time, so perhaps I had a weird version) even before the graphical corruption of my theme occurs, so I would expect to see them right above my theme's release notes.
Perhaps the release notes aren't being registered as "Hey! Package Control! Show this to the user when you upgrade!" Because that message would've helped ease the transition.

**Comment by grotewold** [comment]
Thanks again for helping out! I think it's safe to close now.
