### ISSUE TITLE
Error Highlighting Shifted

### ISSUE THREAD

**Issue by rgant** [SublimeLinter/SublimeLinter-phplint#19]
In this screen shot you can see that the highlighting for the error "undeclared interface class 'UserInterface'" is over ", EquatableIn" instead of "UserInterface".

<img width="544" alt="screen shot 2016-01-20 at 18 15 50" src="https://cloud.githubusercontent.com/assets/710553/12466349/ecfc5172-bfa1-11e5-98a9-1ca3f8d0796e.png">

It's possible that I have configured things incorrectly. I'm just getting back into PHP have many years. However I think I've followed the instructions. I'm running PHPLint 2.1_20151116 installed via Homebrew.(https://github.com/rgant/homebrew-php/blob/up_phplint/Formula/phplint.rb Updating the formula to the latest version here. However this didn't work on 20150305 either.) Sublime Text 3 build 3083, Package Control & SublimeLinter are up to date.

Any help resolving this would be appreciated.

**Comment by grotewold** [comment]
Could you send me the results of running this command:
```
phpl --php-version 5 --print-path relative --print-column-number --tab-size 4 --no-overall path/to/file.php
```

replacing `path/to/file.php` with the appropriate path.

Thanks!

**Comment by rgant** [comment]
[lintout.txt](https://github.com/SublimeLinter/SublimeLinter-phplint/files/99870/lintout.txt)

Trying to introduce the concept of linting, so there are many many errors. It looks like the arrows are pointing at the end of the _thing_, maybe they used to point at the beginning?

Thanks!

**Comment by grotewold** [comment]
Ok, so this is kind of what I expected. Yes, the linter is giving the column but its the last character where the majority of linters give the first character. Example:
```
==== 8:36: ERROR: undeclared interface class `UserInterface'
```
instead of...
```
==== 8:23: ERROR: undeclared interface class `UserInterface'
```

I'm sorry for this inconvenience. I'm not sure if it has always been this way or just recently.

**Comment by rgant** [comment]
I forgot to mention that I am using PHP7.

**Comment by ajmichels** [comment]
The issue here is that this linter is currently set up to only work for PHP5. We will have to update the linter to support specifying the version of PHP to lint for.

You can see at https://github.com/SublimeLinter/SublimeLinter-phplint/blob/master/linter.py#L21 where the version is hard coded into the file.

**Comment by josephtaylor-mn** [comment]
I have just submitted a pull request to add the ability to set the php_version as a setting in the SublimeLinter user settings.

**Comment by ajmichels** [comment]
Great. Thank you. I have started reviewing the code. I will have feedback for you probably by the end of the day.

**Comment by holtjohnson** [comment]
I believe I have the same issue, so I completed @josephtaylor-mn previous work.
![screen shot 2017-07-17 at 11 23 55](https://user-images.githubusercontent.com/1328245/28278404-9aa9eb6c-6ae2-11e7-937f-1c42b53df056.png)

**Comment by braver** [comment]
PHP version will be configurable with #32

**Comment by kublaios** [comment]
Well I am facing this for `PHPLint 4.0_20190206` and `PHP 7.3.7` even though I set PHPLint version to 7 (I think it is default already anyway). How can I trace it?

**Comment by braver** [comment]
Start here: http://www.sublimelinter.com/en/stable/troubleshooting.html

**Comment by kublaios** [comment]
Well the console is full of similar problems to this one: https://github.com/SublimeLinter/SublimeLinter-phplint/issues/19#issuecomment-173934497

Here's a sample file:
```
<?php

class BrokenBat
{
	function returnHome() {
		print $dark;
	}
}
```

And here is the console output when debug mode is on:
```
SublimeLinter: sublime_linter.py:248  Delay linting 'test.php' for 0.0s
INFO:SublimeLinter.sublime_linter:Delay linting 'test.php' for 0.0s
SublimeLinter: linter.py:1056         phplint: Checking lint mode 'background' vs lint reason 'on_load'.  Ok.
INFO:SublimeLinter.lint.linter:phplint: Checking lint mode 'background' vs lint reason 'on_load'.  Ok.
SublimeLinter: #4 linter.py:1073      phplint: linting 'test.php'
INFO:SublimeLinter.lint.linter:phplint: linting 'test.php'
SublimeLinter: #4 linter.py:1576      Running ...

  /Users/batman/Desktop  (working dir)
  $ /usr/local/bin/phpl --print-path relative --print-column-number --no-overall /Users/batman/Desktop/test.php

INFO:SublimeLinter.lint.linter:Running ...

  /Users/batman/Desktop  (working dir)
  $ /usr/local/bin/phpl --print-path relative --print-column-number --no-overall /Users/batman/Desktop/test.php

SublimeLinter: #4 linter.py:1155      phplint: output:
  BEGIN parsing of ../../Desktop/test.php
  1:  <?php
  2:  
  3:  class BrokenBat
  4:  {
  5:    function returnHome() {
  6:      print $dark;

        print $dark;
                               \_ HERE
  ==== 6:28: ERROR: variable $dark does not exist
  7:    }
  8:  }
  END parsing of ../../Desktop/test.php
INFO:SublimeLinter.lint.linter:phplint: output:
  BEGIN parsing of ../../Desktop/test.php
  1:  <?php
  2:  
  3:  class BrokenBat
  4:  {
  5:    function returnHome() {
  6:      print $dark;

        print $dark;
                               \_ HERE
  ==== 6:28: ERROR: variable $dark does not exist
  7:    }
  8:  }
  END parsing of ../../Desktop/test.php
SublimeLinter: sublime_linter.py:482  Linting 'test.php' took 0.13s
INFO:SublimeLinter.sublime_linter:Linting 'test.php' took 0.13s
```

`print $dark;` line has 21 columns but it tries to lint the 28th. Here is the visual output:

<img width="831" alt="phplint" src="https://user-images.githubusercontent.com/1839554/62328576-ce9c3480-b4b3-11e9-84f1-1812aa540164.png">

**Comment by kaste** [comment]
Hi @kublaios!

I don't use `phpl` but... `$ /usr/local/bin/phpl --print-path relative --print-column-number --no-overall /Users/batman/Desktop/test.php` is the default command by this plugin. You said you set the version to 7 but this is not reflected in the `cmd`. 

Does this thing work on the command line? This is usually the question that matters. If it does then some setup must be tweaked, if not the linter itself is in charge. If I would get the same nonsense output on the cli (`\_ HERE` LOL) I would rather look at stackoverflow or the linters repo.

**Comment by kublaios** [comment]
Thanks @kaste, I just ran the command you provided and here is the output:
```
BEGIN parsing of Desktop/test.php
1:	<?php
2:	
3:	class BrokenBat
4:	{
5:		function returnHome() {
6:			print $dark;

			print $dark;
	                   \_ HERE
==== 6:28: ERROR: variable $dark does not exist
7:		}
8:	}
END parsing of Desktop/test.php
```

Which means that you are right, it's not related to the plugin but the linter itself. Thanks!
