### ISSUE TITLE
Syntax highlighting changed colors

### ISSUE THREAD

**Issue by simplenotezy** [SublimeLinter/SublimeLinter-phplint#22]
I tried to install this package, but decided to uninstall it again because of https://github.com/SublimeLinter/SublimeLinter-phplint/issues/21

However, now my syntax highlighting (colors etc) have changed. Why? Any idea how I can revert this?

**Comment by ajmichels** [comment]
There is no code in this package that changes syntax highlighting, so something else must have caused this issue for you. As far as how to revert it I am not sure there is any answer I can give you.

**Comment by simplenotezy** [comment]
That is strange. Because it happend directly after installing phplint

**Comment by ajmichels** [comment]
Are you sure you didn't install another package around the same time? There is only one file that runs with this package and it doesn't include any code to change syntax highlighting. https://github.com/SublimeLinter/SublimeLinter-phplint/blob/master/linter.py Perhaps you installed the base SublimeLinter package at the same time?
