### ISSUE TITLE
No sucess in installation at all

### ISSUE THREAD

**Issue by przeslijmi** [SublimeLinter/SublimeLinter-phplint#24]
Hello.

I have:
- Sublime Text 3 (Build 3114)
- SublimeLinter v3.7.4
- SublimeLinter-phplint v2.0.0

I'm trying to use it. Without success. What I've done:
1. installed node `node -v` returns v6.3.0
2. installed npm `npm -v` returns v3.10.3
3. installed phplint `npm install phplint` with result:

```
C:\Windows\system32
`-- phplint@1.7.1
  +-- async@1.5.2
  +-- cache-swap@0.2.3
  | +-- graceful-fs@4.1.5
  | +-- mkdirp@0.5.1
  | | `-- minimist@0.0.8
  | +-- object-assign@4.1.0
  | `-- rimraf@2.5.4
  |   `-- glob@7.0.5
  |     `-- fs.realpath@1.0.0
  `-- globby@3.0.1
    +-- array-union@1.0.2
    | `-- array-uniq@1.0.3
    +-- arrify@1.0.1
    +-- glob@5.0.15
    | +-- inflight@1.0.5
    | | `-- wrappy@1.0.2
    | +-- inherits@2.0.1
    | +-- minimatch@3.0.2
    | | `-- brace-expansion@1.1.6
    | |   +-- balanced-match@0.4.2
    | |   `-- concat-map@0.0.1
    | +-- once@1.3.3
    | `-- path-is-absolute@1.0.0
    +-- pify@2.3.0
    `-- pinkie-promise@1.0.0
      `-- pinkie@1.0.0

npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\System32\pac
kage.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.
```
1. tried to use it with `npm i -g phplint` and I've got:

```
C:\Users\Karol\AppData\Roaming\npm\phplint -> C:\Users\Karol\AppData\Roaming\npm
\node_modules\phplint\cli.js
C:\Users\Karol\AppData\Roaming\npm
`-- phplint@1.7.1
```
1. in my system variables there are among others:

```
c:\__Moje\wamp64\bin\php\php5.6.16
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Program Files\nodejs\
C:\Users\Karol\AppData\Roaming\npm\
C:\Program Files\Git\
c:\__Moje\wamp64\bin\php\php5.6.16\
```

When starting Sublime Text i see in console: `SublimeLinter: WARNING: phplint deactivated, cannot locate 'phpl'`.

That is true - there is no such a file anywhere. Why does SublimeLinter-phplint expects file that does not exists on phplint package? How to solve this?

Please help.

**Comment by ajmichels** [comment]
SublimeLinter expects phpl which is the binary for PHPLint to be available in your system path. If you open an instance of Command Prompt and type `phpl --version` and hit enter you should see the version information for PHPLint. If not than PHPLint is not installed correctly or it is not available on your system path.

**Comment by ajmichels** [comment]
Ah! The issue you are having is that the npm package called "phplint" (https://www.npmjs.com/package/phplint) is not the linter you are looking for, it is just a wrapper around the linter built into PHP or `php -l`. You should go to http://www.icosaedro.it/phplint/ and follow the installation instructions there.

I will look into updating the project readme file to include some installation instructions for Windows.

**Comment by przeslijmi** [comment]
Hey.

Your help made this thing working. Unfortunately neither -phplint, nor -phpmd, nor -phpcs didn't meet my expectations. They were calling too many errors (like undefined PHP functions :!:) or not calling them at all. Upgrade from ST2 to ST3 made this package not useful for me :(

It was great to have all misteakes shown before (like spaces on the end of a line, wrong indentations, wrong notations, etc.) but now it seems impossible.... :(

Thanks for your help.

**Comment by ajmichels** [comment]
Hmm. I am not very familiar with how the phplint linter itself is intended to work. I have more experience using phpcs and phpmd. 

phpmd (PHP Mess Detector) is intended to help you maintain clean and simple code. It isn't really meant to be used for enforcing a specific style of coding (spaces, indentation, line breaks, etc.).

phpcs (PHP Code Sniffer) on the other hand is very much meant to maintain a specific style of coding and comes with a number of predefined standards to follow such as PSR-2 and Zend. However, it is very customizable and can be configured to meet your specific needs. You can even write your own sniffs if you need to.

What is it specifically that you are hoping to get out of these linters? I imagine phpcs can do what you need you will probably just need to adjust its configuration.

**Comment by braver** [comment]
I'm closing this discussion because it doesn't seem to be about an issue with the plugin. There are several ways to lint php, this plugin doesn't have an opinion about that: there are also several SL plugins if you want to use another linter.
