### ISSUE TITLE
Popup alert on file save.

### ISSUE THREAD

**Issue by ethaniel** [SublimeLinter/SublimeLinter-phplint#27]
Hello! Do you guys know if it's possible to add an option to pop up an alert if I'm trying to save a file which has a php error?

**Comment by ajmichels** [comment]
I am not familiar with a way of doing what you described.

**Comment by ethaniel** [comment]
Maybe you could escalate this question to Sublime devs? It would be awesome to catch errors before they get loaded into production. (we're a small company and all our edits go live immediately).

**Comment by ajmichels** [comment]
We don't have any special relationship with the people who develop the core of Sublime, you would be just as likely to get a response from them as we would.

I recommend you look into Continuous Integration and Continuous Delivery best practices. There are a lot of free and/or inexpensive tools out there that you could be using. You could also look into using Git hooks to run scripts such as PHPlint against your code before it will be allowed to be committed.

**Comment by ethaniel** [comment]
Ah, got you! Thank you for the information. Will definately look into it.
