### ISSUE TITLE
Unresolved function X

### ISSUE THREAD

**Issue by slifin** [SublimeLinter/SublimeLinter-phplint#30]
On nearly all functions in my project I get the lint error ```unresolved function``` if the function is not directly defined in the file I'm currently working in, how do I get the linter to traverse the project?

I'm running PHP 7.0 if it makes any difference to this behaviour

**Comment by slifin** [comment]
Looks like there's a modules folder that contains stubs for all core php and there used to be a setting --modules-path but that's been taken out now

**Comment by legend80s** [comment]
+1

**Comment by tomvo** [comment]
Besides also seeing this on my custom functions I see this also on native functions like `str_replace`

**Comment by arvidbjorkstrom** [comment]
Getting this as well, and it made me disable the phplint linter, now just running the regular php linter and phpcs.

**Comment by pcoughlin** [comment]
About to disable and uninstall. This 'reported error' is not helping.

**Comment by quantumwebco** [comment]
I'm still getting this issue. How to resolve?

**Comment by MatthieuArzel** [comment]
Still getting this error two.

**Comment by kaste** [comment]
Hm, please post what you run on the command line. Which command, from which working dir.

**Comment by MatthieuArzel** [comment]
I installed it back trough my terminal 
> brew install homebrew/php/phplint
Then it fired thoses alerts.
Maybe i got some issues with multiples php folder (php, php7…)

**Comment by kaste** [comment]
I would first make it work on the command line. Then we will compare that to what the plugin here does.

**Comment by kaste** [comment]
If you enable debug mode in SublimeLinter you will see what cmd this plugin invokes/runs. So you already can play with that. Copy the cmd, modify it. Maybe the working dir is wrong. Etc.

**Comment by MatthieuArzel** [comment]
Hey Kaste. 
Thx for all the tips, I'll have a closer look Wednesday back at work 👍

**Comment by braver** [comment]
@MatthieuArzel got any further with it?
