### ISSUE TITLE
PHP 7.2 deprecated 'track_errors' and '__autoload()'

### ISSUE THREAD

**Issue by pierrefaure** [SublimeLinter/SublimeLinter-phplint#31]
Using **php 7.2**

**Typing**
`/usr/local/bin/phpl --version`
in the console (or opening/saving a file in sublime)
I got the following errors:
```
PHP Deprecated:  Directive 'track_errors' is deprecated in Unknown on line 0
Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
Uncaught InternalException: E_DEPRECATED: __autoload() is deprecated, use spl_autoload_register() instead in /usr/local/Cellar/phplint/3.0-20160307/stdlib/errors.php:172
Stack trace:
#0 /usr/local/Cellar/phplint/3.0-20160307/stdlib/all.php(3): phplint_error_handler(8192, '__autoload() is...', '/usr/local/Cell...', 80, Array)
#1 /usr/local/Cellar/phplint/3.0-20160307/stdlib/all.php(3): require_once()
#2 /usr/local/Cellar/phplint/3.0-20160307/stdlib/it/icosaedro/lint/PHPLint.php(4): require_once('/usr/local/Cell...')
#3 {main}
```

Looks like `__autoload()` and `track_errors` are deprecated: http://php.net/manual/en/migration72.deprecated.php

**Temporary fix for mac (using brew):**
`brew unlink php72`
`brew install php71`
`brew link php71` (you might not need this one, install should link it)

Restart sublime + console and it works.

**Comment by MikeDoouglas** [comment]
**The track_errors was deprecated in PHP 7.2**

In php.ini change 
`track_errors=On`
to
`track_errors=Off`

> When the track_errors ini setting is enabled, a $php_errormsg variable is created in the local scope when a non-fatal error occurs. Given that the preferred way of retrieving such error information is by using error_get_last(), this feature has been deprecated.

Font: [http://php.net/manual/pt_BR/migration72.deprecated.php](url)

**Comment by braver** [comment]
Thanks for reporting this, but the SublimeLinter plugin simply calls phplint. These issues should be reported over at phplint itself.

**Comment by everaldomatias** [comment]
> **The track_errors was deprecated in PHP 7.2**
> 
> In php.ini change
> `track_errors=On`
> to
> `track_errors=Off`
> 
> > When the track_errors ini setting is enabled, a $php_errormsg variable is created in the local scope when a non-fatal error occurs. Given that the preferred way of retrieving such error information is by using error_get_last(), this feature has been deprecated.
> 
> Font: [http://php.net/manual/pt_BR/migration72.deprecated.php](url)

Work for me @MikeDoouglas. Thank so much!!

**Comment by rpsc1990** [comment]
> **The track_errors was deprecated in PHP 7.2**
> 
> In php.ini change
> `track_errors=On`
> to
> `track_errors=Off`
> 
> > When the track_errors ini setting is enabled, a $php_errormsg variable is created in the local scope when a non-fatal error occurs. Given that the preferred way of retrieving such error information is by using error_get_last(), this feature has been deprecated.
> 
> Font: [http://php.net/manual/pt_BR/migration72.deprecated.php](url)

Thanks ! it worked for me.
