### ISSUE TITLE
Unresolved Function Error w/ Native Functions 

### ISSUE THREAD

**Issue by jvanalst** [SublimeLinter/SublimeLinter-phplint#35]
I ran into this today where none of the native PHP functions can be resolved by PHPLint.

I ran it in debug mode and got:

```
/usr/local/bin/phpl --php-version 5 --print-path relative --print-column-number --tab-size 4 --no-overall ./401error.php 
BEGIN parsing of 401error.php
1:	<html>
2:	<head>
3:	<title>Error - Not authenticated</title>
4:	</head>
5:	<body>
6:	<h1>Error - Not authenticated</h1>
7:	Please log in.
8:	</body>
9:	</html>
10:	
11:	<?php
12:	$foo = array(2);
13:	
14:	$foo2 = array_pop($foo);

	$foo2 = array_pop($foo);
	                  \_ HERE
==== 14:19: ERROR: unresolved function array_pop
15:	
16:	?>
==== ?:?: notice: this package is not a library:
	Bare textual content detected before PHP opening tag: "<html>\n<head>\n<title".
END parsing of 401error.php
```

PS. I'm using PHP 7.2.1 on OS X through brew, but changing the ``--php-version`` has no effect.

See Also:
https://github.com/SublimeLinter/SublimeLinter-phplint/issues/30

**Comment by jvanalst** [comment]
```
phpl --version
PHPLint 3.2_20180727
Copyright 2018 by icosaedro.it di Umberto Salsi
This is free software; see the license for copying conditions.
More info: http://www.icosaedro.it/phplint
```

**Comment by kaste** [comment]
Take a look  http://www.icosaedro.it/phplint/FAQ.html#H9_Can_I_turn_off_some_boring_error_PHPLint_signals? and  http://www.icosaedro.it/phplint/phplint2/doc/reference.htm?p=importingmodules

**Comment by tobsn** [comment]
same here:
PHPLint 3.2_20180727
PHP 7.2.8 (cli)

Reports all native functions as unresolved. I read the part about loading modules but there must be a simpler way than adding all those modules to every file...

**Comment by kazitanvirahsan** [comment]
Getting all the built-in function unrecognized in phplint reporting.

**Comment by braver** [comment]
I this caused with the way we run PHPLint, or is it an effect of the way PHPLint works anyway?

**Comment by kaste** [comment]
This is how the linter works. The linter basically wants that you add a kind of typing info to your files. Explicit over implicit style.

**Comment by braver** [comment]
Makes sense.
